title: Everyday Learning Analytics @ 2nd-year Masters (Spring 2017)
author: Luis P. Prieto
email: lprisan@tlu.ee
description: A prototype of what Everyday Learning Analytics might look like
baseurl: /EverydayLA-Prototype4Terje

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
