---
title: "Everyday LA: Vihula W.S. (13.01.2017)"
output: 
  flexdashboard::flex_dashboard
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(gsheet)
suppressMessages(library(dplyr))
library(data.table)
library(rvest)
library(ggplot2)
library(ineq)
library(syuzhet)
library(tm)
library(wordcloud)
library(SnowballC)
library(stringi)
library(stringr)

URL_Q_Presenter <- 'https://docs.google.com/spreadsheets/d/1cEz64I2_YmwwZfVevH2kpqXwUPi79LzV43nK374jE0A/edit?usp=sharing'
URL_Q_Audience <- 'https://docs.google.com/spreadsheets/d/1hQTcSdw7r04GOyn4RyZFA-yGaU0mkoVF4_-GkdBcKf0/edit?usp=sharing'
URL_Q_Feedback <- 'https://docs.google.com/spreadsheets/d/1QQ8k8fjLTDxXv7OJ9MaJC2dPVnbss2MAYki1k8rV3YE/edit?usp=sharing'
URL_Q_Wrap <- 'https://docs.google.com/spreadsheets/d/1K3YTYAyZ1RinpxM4wrQXmlbXvwVrKrp5Yn7nS_XlImE/edit?usp=sharing'


# Define the data gathering function here? possibly using
# http://shiny.rstudio.com/reference/shiny/latest/reactivePoll.html
# http://shiny.rstudio.com/gallery/reactive-poll-and-file-reader.html

pollSpreadsheet <- function(url, namesCol=NULL, factors=NULL){
  data <- reactivePoll(5000, session,
                     readLastTimestamp <- function(){
                        # We read the latest response timestamp
                        data <- as.data.frame(gsheet2tbl(url))
                        if(nrow(data)>0 & ncol(data)>1){
                          data[nrow(data),1]
                        }else{
                          ""
                        }
                      },
                     readValue <- function(){
                        data <- as.data.frame(gsheet2tbl(url))
                        #We clean it up a bit
                        if(!is.null(namesCol) & length(namesCol)>0){
                          names(data) <- namesCol 
                        }
                        if(!is.null(factors) & length(factors)>0){
                          for(f in factors){
                            data[,f] <- as.factor(data[,f])
                          }  
                        }
                        data
                      })
  data
}


presenterData <- pollSpreadsheet(URL_Q_Presenter, 
                          c("Timestamp","Name","MainQ","OtherQ"),
                          c("Name"))

presenterD <- reactive({
  data <- presenterData()
  data
})


audienceData <- pollSpreadsheet(URL_Q_Audience, 
                          c("Timestamp","Name","Understanding","MainQ","OtherQ","Audience.Name"),
                          c("Name"))

audienceD <- reactive({
  data <- audienceData()
  data
})


feedbackData <- pollSpreadsheet(URL_Q_Feedback, 
                          c("Timestamp","Name","Question","Feedback","Satisfaction"),
                          c("Name"))

feedbackD <- reactive({
  data <- feedbackData()
  data
})

wrapData <- pollSpreadsheet(URL_Q_Wrap, 
                          c("Timestamp","Chair.Name","Lessons.Students","Lessons.Audience"),
                          c("Chair.Name"))

wrapD <- reactive({
  data <- wrapData()
  data
})





convertFactor <- function(values){
  print(values)
  if(!is.null(values) & length(values)>0){
    newvals = numeric()
    for(val in values){
      if(grepl(as.character(val),"Strongly agree",fixed = T)){
        newval = 5
      }else if(grepl(as.character(val),"Agree",fixed = T)){
        newval = 4
      }else if(grepl(as.character(val),"Neither agree nor disagree",fixed = T)){
        newval = 3
      }else if(grepl(as.character(val),"Disagree",fixed = T)){
        newval = 2
      }else if(grepl(as.character(val),"Strongly disagree",fixed = T)){
        newval = 1
      }else if(grepl(as.character(val),"Not Applicable",fixed = T)){
        newval = NA
      }
      newvals <- c(newvals, newval)
    }
    print(newvals)
    newvals
  }else{
    values
  }
}



      count_words <- function(s){
        #count <- as.numeric(stri_stats_latex(s)['Words'])
        count <- vapply(strsplit(s, "\\W+"), length, integer(1))
        count
      }

  clean_vector <- function(v){
    newv <- v[v!=""]
    newv2 <- newv[length(newv)>1]
    newv2
  }
      
      
sessions <- read.csv(file = "Sessions.csv", encoding="UTF-8", stringsAsFactors=FALSE)

```


Overall
=====================================  
    
Column 1 
-------------------------------------

### Sessions recorded and wrapped up

```{r}

renderValueBox({
              data <- wrapD()
              sessions <- unique(data$Chair.Name)
              valueBox(
                value=length(sessions),
                icon = "fa-microphone",
                color="primary")
                })

```   

### Student / Audience open questions


```{r}

renderValueBox({
  
   data <- presenterD()
 studentQ1 <- data[,"MainQ"]
 studentQ2 <- data[,"OtherQ"]
 if(length(studentQ1)>0 & length(studentQ2)>0){
  qs1 <- unlist(string.break.line(paste(studentQ1,studentQ2,sep="\n")))
 }else if(length(studentQ1)>0){
  qs1 <- unlist(string.break.line(studentQ1))
 }else if(length(studentQ2)>0){
  qs1 <- unlist(string.break.line(studentQ2))
 }else{
   qs1 <- character(0)
 }

 qs1 <- clean_vector(qs1)
 
  data <- audienceD()
 audienceQ1 <- data[,"MainQ"]
 audienceQ2 <- data[,"OtherQ"]
 if(length(audienceQ1)>0 & length(audienceQ2)>0){
  qs2 <- unlist(string.break.line(paste(audienceQ1,audienceQ2,sep="\n")))
 }else if(length(audienceQ1)>0){
  qs2 <- unlist(string.break.line(audienceQ1))
 }else if(length(audienceQ2)>0){
  qs2 <- unlist(string.break.line(audienceQ2))
 }else{
   qs2 <- character(0)
 }

 qs2 <- clean_vector(qs2)
 
  message=paste(length(qs1), "/", length(qs2))
  
              valueBox(
                value=message,
                icon = "fa-question",
                color="warning")
                })

```   

### Audience comprehension



```{r}

renderPlot({
  aud <- audienceD()
  d <- aud
  if(nrow(d)>0){
    ggplot(d, aes(x=Understanding))+geom_density(alpha=0.2, fill="green")+theme_bw()+xlim(0,10)+geom_vline(xintercept = mean(d$Understanding))
  }
})
```

### Questions discussed / Pieces of feedback

```{r}

renderValueBox({
              fb <- feedbackD()
              d <- fb
              f <- unlist(string.break.line(paste(fb$Feedback,sep="\n")))
              f <- clean_vector(f)
              message <- paste(nrow(d),"/",length(f))
              valueBox(
                value=message,
                icon = "fa-comments",
                color="danger")
                })
```


### Student satisfaction about the feedback


```{r}

renderPlot({
  fb <- feedbackD()
  d <- fb
  if(nrow(d)>0){
    ggplot(d, aes(x=Satisfaction))+geom_density(alpha=0.2, fill="red")+theme_bw()+xlim(0,10)+geom_vline(xintercept = mean(d$Satisfaction))
  }
})
```

### Lessons learned by students / by audience

```{r}

renderValueBox({
   data <- wrapD()
   d <- data[,]
   les.stu <- paste(d$Lessons.Students,sep="\n")
   les.aud <- paste(d$Lessons.Audience,sep="\n")
   
   les.stu <- clean_vector(les.stu)
   les.aud <- clean_vector(les.aud)
   
   n_les.stu <- 0
   n_les.aud <- 0
   if(length(les.stu)>0){
    n_les.stu <- length(unlist(string.break.line(les.stu)))
   }
   if(length(les.aud)>0){
    n_les.aud <- length(unlist(string.break.line(les.aud)))
   }
   message <- paste(n_les.stu,"/",n_les.aud)
  valueBox(value=message,
                icon = "fa-graduation-cap",
                color="info")

})

```



Column 2
-------------------------------------

### Open questions word cloud

```{r}

renderPlot({
  pr <- presenterD()
  au <- audienceD()
  
  d <- character(0)
  if(nrow(pr)>0){
    d <- c(d,pr$MainQ,pr$OtherQ)
  }
  if(nrow(au)>0){
    d <- c(d,au$MainQ,au$OtherQ)
  }
  
  d <- unlist(string.break.line(paste(d,sep="\n")))
  
  d <- clean_vector(d)
  
  if(length(d)>0){
    corpus <- Corpus(VectorSource(d))
    corpus <- tm_map(corpus, removePunctuation)
    corpus <- tm_map(corpus, tolower)
    corpus <- tm_map(corpus, removeWords, stopwords("english"))
    corpus <- tm_map(corpus, stemDocument)
    corpus <- tm_map(corpus, PlainTextDocument)
    wordcloud(corpus, max.words=100, random.order=F)
  }
})
```



### Feedback word cloud

```{r}

renderPlot({
  fb <- feedbackD()
  d <- fb
  d2 <- clean_vector(unlist(string.break.line(d$Feedback)))
  if(length(d2)>0){
    corpus <- Corpus(VectorSource(d2))
    corpus <- tm_map(corpus, removePunctuation)
    corpus <- tm_map(corpus, tolower)
    corpus <- tm_map(corpus, removeWords, stopwords("english"))
    corpus <- tm_map(corpus, stemDocument)
    corpus <- tm_map(corpus, PlainTextDocument)
    wordcloud(corpus, max.words=100, random.order=F)
  }
})
```

Column 3
-------------------------------------


### Lessons word cloud

```{r}

renderPlot({
  wr <- wrapD()
  d <- c(wr$Lessons.Students,wr$Lessons.Audience)
  d <- clean_vector(d)
  if(length(d)>0){
    corpus <- Corpus(VectorSource(d))
    corpus <- tm_map(corpus, removePunctuation)
    corpus <- tm_map(corpus, tolower)
    corpus <- tm_map(corpus, removeWords, stopwords("english"))
    corpus <- tm_map(corpus, stemDocument)
    corpus <- tm_map(corpus, PlainTextDocument)
    wordcloud(corpus, max.words=100, random.order=F)
  }
})
```


Session
=====================================



```{r}

chairs <- sort(unique(sessions$Chair.Name))

selectInput("chair", label = "Please select the session chair's name:",
            choices = chairs, selected = chairs[1])
```




Column 1
-------------------------------------

### Students presented

```{r}

renderValueBox({
              sessionstu <- sessions[sessions$Chair.Name == input$chair,"Student.Name"]
              aud <- audienceD()
              pres <- presenterD()
              d <- pres[pres$Name %in% sessionstu,]
              valueBox(
                value=nrow(d),
                icon = "fa-user",
                color="primary")
                })
```

### Open questions discussed 

```{r}

renderValueBox({
              sessionstu <- sessions[sessions$Chair.Name == input$chair,"Student.Name"]
              fb <- feedbackD()
              d <- fb[fb$Name %in% sessionstu,]
              valueBox(
                value=nrow(d),
                icon = "fa-question",
                color="warning")
                })
```


### Session words / lines of feedback 

```{r}

renderValueBox({
              sessionstu <- sessions[sessions$Chair.Name == input$chair,"Student.Name"]
              fb <- feedbackD()
              d <- fb[fb$Name %in% sessionstu,]
              message="0 / 0"
              if(nrow(d)>0){
                totalfb <- paste(d$Feedback, sep = "\n")
                lines <- clean_vector(unlist(string.break.line(totalfb)))
                wc <- sum(sapply(totalfb,FUN = count_words))
                message <- paste(length(lines),"/",wc)
                  
              }
              valueBox(
                  value=message,
                  icon = "fa-pencil",
                  color="success")
                })
```



### Session feedback word cloud

```{r}

renderPlot({
  sessionstu <- sessions[sessions$Chair.Name == input$chair,"Student.Name"]
  fb <- feedbackD()
  d <- fb[fb$Name %in% sessionstu,]
  if(nrow(d)>0){
    d2 <- clean_vector(d$Feedback)
    corpus <- Corpus(VectorSource(d2))
    corpus <- tm_map(corpus, removePunctuation)
    corpus <- tm_map(corpus, tolower)
    corpus <- tm_map(corpus, removeWords, stopwords("english"))
    corpus <- tm_map(corpus, stemDocument)
    corpus <- tm_map(corpus, PlainTextDocument)
    wordcloud(corpus, max.words=100, random.order=F)
  }
})
```


Column 2
-------------------------------------

### Audience comprehension of presentations


```{r}

renderPlot({
  sessionstu <- sessions[sessions$Chair.Name == input$chair,"Student.Name"]
  aud <- audienceD()
  d <- aud[aud$Name %in% sessionstu,]
  if(nrow(d)>0){
    ggplot(d, aes(x=Understanding))+geom_density(alpha=0.2, fill="green")+theme_bw()+xlim(0,10)+geom_vline(xintercept = mean(d$Understanding))
  }
})
```



### Student satisfaction with feedback


```{r}

renderPlot({
  sessionstu <- sessions[sessions$Chair.Name == input$chair,"Student.Name"]
  fb <- feedbackD()
  d <- fb[fb$Name %in% sessionstu,]
  if(nrow(d)>0){
    ggplot(d, aes(x=Satisfaction))+geom_density(alpha=0.2, fill="red")+theme_bw()+xlim(0,10)+geom_vline(xintercept = mean(d$Satisfaction))
  }
})
```

Column 3
-------------------------------------

### Lessons learned

```{r}

library(Hmisc)

renderTable({
 data <- wrapD()
 print(data)
 print(input$chair)
 d <- data[data$Chair.Name==input$chair,]
 les.stu <- d$Lessons.Students
 les.aud <- d$Lessons.Audience
 if(length(les.stu)>0 & length(les.aud)>0){
  qs <- unlist(string.break.line(paste(les.stu,les.aud,sep="\n")))
 }else if(length(les.stu)>0){
  qs <- unlist(string.break.line(les.stu))
 }else if(length(les.aud)>0){
  qs <- unlist(string.break.line(les.aud))
 }else{
   qs <- c("")
 }
 qs <- clean_vector(qs)
 data.frame(Lessons=qs)
 
})

```


Student
=====================================



```{r}

students <- sort(sessions$Student.Name)

selectInput("student", label = "Please select the presenting student's name:",
            choices = students, selected = students[1])
```


Column 1
-------------------------------------

### How much did audience understand the presentation?

```{r}

renderPlot({
  data <- audienceD()
  d <- data[data$Name==input$student,]
  ggplot(d, aes(x=Understanding))+geom_density(alpha=0.2, fill="green")+theme_bw()+xlim(0,10)+geom_vline(xintercept = mean(d$Understanding))
})
```


### Student open questions

```{r}

library(Hmisc)

renderTable({
 data <- presenterD()
 studentQ1 <- data[data$Name == input$student,"MainQ"]
 studentQ2 <- data[data$Name == input$student,"OtherQ"]
 if(length(studentQ1)>0 & length(studentQ2)>0){
  qs <- unlist(string.break.line(paste(studentQ1,studentQ2,sep="\n")))
 }else if(length(studentQ1)>0){
  qs <- unlist(string.break.line(studentQ1))
 }else if(length(studentQ2)>0){
  qs <- unlist(string.break.line(studentQ2))
 }else{
   qs <- c("")
 }
 qs <- clean_vector(qs)
 data.frame(Question=qs)
 
})


```


### Open questions contributed by audience

```{r}

library(Hmisc)

renderTable({
 data <- audienceD()
 audienceQ1 <- data[data$Name == input$student,"MainQ"]
 audienceQ2 <- data[data$Name == input$student,"OtherQ"]
 if(length(audienceQ1)>0 & length(audienceQ2)>0){
  qs <- unlist(string.break.line(paste(audienceQ1,audienceQ2,sep="\n")))
 }else if(length(audienceQ1)>0){
  qs <- unlist(string.break.line(audienceQ1))
 }else if(length(audienceQ2)>0){
  qs <- unlist(string.break.line(audienceQ2))
 }else{
   qs <- c("")
 }
 qs <- clean_vector(qs)
 data.frame(Question=qs)
 
})


```


Column 2
-------------------------------------

### Questions discussed

```{r}

renderValueBox({
              data <- feedbackD()
              d <- data[data$Name==input$student,]
              valueBox(
                value=nrow(d),
                icon = "fa-question",
                color="warning")
                })
```

### Total feedback gathered (lines / words)

```{r}

renderValueBox({
              data <- feedbackD()
              d <- data[data$Name==input$student,]
              message="0 / 0"
              if(nrow(d)>0){
                totalfb <- paste(d$Feedback, sep = "\n")
                lines <- clean_vector(unlist(string.break.line(totalfb)))
                wc <- sum(sapply(totalfb,FUN = count_words))
                message <- paste(length(lines),"/",wc)
                
              }
              valueBox(
                  value=message,
                  icon = "fa-pencil",
                  color="success")
                })
```



### Feedback word cloud

```{r}

renderPlot({
  data <- feedbackD()
  d <- data[data$Name==input$student,]
  if(nrow(d)>0){
    d2 <- clean_vector(d$Feedback)
    corpus <- Corpus(VectorSource(d2))
    corpus <- tm_map(corpus, removePunctuation)
    corpus <- tm_map(corpus, tolower)
    corpus <- tm_map(corpus, removeWords, stopwords("english"))
    corpus <- tm_map(corpus, stemDocument)
    corpus <- tm_map(corpus, PlainTextDocument)
    wordcloud(corpus, max.words=100, random.order=F)
  }
})
```

<!-- ### Student satisfaction with feedback -->


```{r}
# TODO: remove this graph??

# renderPlot({
#   data <- feedbackD()
#   d <- data[data$Name==input$student,]
#   ggplot(d, aes(x=Satisfaction))+geom_density(alpha=0.2, fill="red")+theme_bw()+xlim(0,10)+geom_vline(xintercept = mean(d$Satisfaction))
# })
```

Column 3
-------------------------------------


### Feedback

```{r}
library(Hmisc)

renderTable({
 data <- feedbackD()
 fb <- data[data$Name == input$student,c("Question","Feedback")]
 if(nrow(fb)>0){
  fb
 }
})


```
