---
title: "Everyday LA: CEEI Seminar (14.12.2016)"
output: 
  flexdashboard::flex_dashboard
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(gsheet)
suppressMessages(library(dplyr))
library(data.table)
library(rvest)
library(ggplot2)
library(ineq)
library(syuzhet)
library(tm)
library(wordcloud)
library(SnowballC)
library(stringi)
library(stringr)

URL_Q1 <- 'https://docs.google.com/spreadsheets/d/1dEkNCHX1QvUrKTA13GPAYqDm4O8H9GbLlTaxbdiSPaM/edit?usp=sharing'
URL_Q2 <- 'https://docs.google.com/spreadsheets/d/18OWx3ZO21Y6XSn5C4Sittm5EJpt5MYUbkeOKDYLl1nY/edit?usp=sharing'
URL_Q3 <- 'https://docs.google.com/spreadsheets/d/19LFZqJGADUguWJMJKDCrwSa453dBXn39BDiTa0MGbwM/edit?usp=sharing'
URL_Q4 <- 'https://docs.google.com/spreadsheets/d/1CJtYYXZbNm23O1e1mNbCx7MmeCcOiVBYT6FYpuuWGns/edit?usp=sharing'
URL_Q5a <- 'https://docs.google.com/spreadsheets/d/1g8NfeWzBkm57tsGri_S1VdxdvoVlCl5oyMQI1WdHNJI/edit?usp=sharing'
URL_Q5b <- 'https://docs.google.com/spreadsheets/d/1MaFd6NwJmL0RT6CVgXorPAvhIovo2ZyT-ytKahlnB_o/edit?usp=sharing'
URL_Q5c <- 'https://docs.google.com/spreadsheets/d/123WbL1JqJILtQaltMEJ0KY7LoRrHNuVaniBCeVTVNts/edit?usp=sharing'
URL_Q5d <- 'https://docs.google.com/spreadsheets/d/1ZiHK1RjyfgePPkImx7UkI5SW0ARrk-F-oZmOZ5h0G0I/edit?usp=sharing'
URL_Q6 <- 'https://docs.google.com/spreadsheets/d/1Ph_-ne6Jlg4WH0li4cZ_ASCfuVLv84yAoJHwPIiSj1M/edit?usp=sharing'
URL_Q7 <- 'https://docs.google.com/spreadsheets/d/1U13iH7hCrW3RK85NHQZnkMqyXnh70YWhF7Sj0-J_Duw/edit?usp=sharing'


# Define the data gathering function here? possibly using
# http://shiny.rstudio.com/reference/shiny/latest/reactivePoll.html
# http://shiny.rstudio.com/gallery/reactive-poll-and-file-reader.html

pollSpreadsheet <- function(url, namesCol=NULL, factors=NULL){
  data <- reactivePoll(5000, session,
                     readLastTimestamp <- function(){
                        # We read the latest response timestamp
                        data <- as.data.frame(gsheet2tbl(url))
                        if(nrow(data)>0 & ncol(data)>1){
                          data[nrow(data),1]
                        }else{
                          ""
                        }
                      },
                     readValue <- function(){
                        data <- as.data.frame(gsheet2tbl(url))
                        #We clean it up a bit
                        if(!is.null(namesCol) & length(namesCol)>0){
                          names(data) <- namesCol 
                        }
                        if(!is.null(factors) & length(factors)>0){
                          for(f in factors){
                            data[,f] <- as.factor(data[,f])
                          }  
                        }
                        data
                      })
  data
}


q1data <- pollSpreadsheet(URL_Q1, 
                          c("Timestamp","Homework","Agree.Feedback","Personal.Goals"),
                          c("Homework"))

homework <- reactive({
  data <- q1data()
  data
})

q2data <- pollSpreadsheet(URL_Q2, 
                          c("Timestamp","Attention.LivingLabs","Understanding.LivingLabs","Implication.LivingLabs",
                            "Attention.STEM","Understanding.STEM","Implication.STEM",
                            "Attention.InformalWP","Understanding.InformalWP","Implication.InformalWP",
                            "Attention.Inclusive","Understanding.Inclusive","Implication.Inclusive",
                            "Name","Email"),
                          c("Implication.LivingLabs","Implication.STEM","Implication.InformalWP","Implication.Inclusive"))

groups <- reactive({
  data <- q2data()
  data
})

q7data <- pollSpreadsheet(URL_Q7, 
                          c("Timestamp","Engaging","Interesting","Apply.Teaching",
                            "Apply.Research","LA.Definition","Comments","Goals.Fulfilled"),
                          c("Engaging","Interesting","Apply.Teaching",
                            "Apply.Research","Goals.Fulfilled"))

feedback <- reactive({
  data <- q7data()
  data
})

convertFactor <- function(values){
  print(values)
  if(!is.null(values) & length(values)>0){
    newvals = numeric()
    for(val in values){
      if(grepl(as.character(val),"Strongly agree",fixed = T)){
        newval = 5
      }else if(grepl(as.character(val),"Agree",fixed = T)){
        newval = 4
      }else if(grepl(as.character(val),"Neither agree nor disagree",fixed = T)){
        newval = 3
      }else if(grepl(as.character(val),"Disagree",fixed = T)){
        newval = 2
      }else if(grepl(as.character(val),"Strongly disagree",fixed = T)){
        newval = 1
      }else if(grepl(as.character(val),"Not Applicable",fixed = T)){
        newval = NA
      }
      newvals <- c(newvals, newval)
    }
    print(newvals)
    newvals
  }else{
    values
  }
}


q5LLdata <- pollSpreadsheet(URL_Q5a, 
                          c("Timestamp","Idea"))

inboxLL <- reactive({
  data <- q5LLdata()
  data
})

q5STEMdata <- pollSpreadsheet(URL_Q5b, 
                          c("Timestamp","Idea"))

inboxSTEM <- reactive({
  data <- q5STEMdata()
  data
})

q5IWPdata <- pollSpreadsheet(URL_Q5c, 
                          c("Timestamp","Idea"))

inboxIWP <- reactive({
  data <- q5IWPdata()
  data
})

q5IEdata <- pollSpreadsheet(URL_Q5d, 
                          c("Timestamp","Idea"))

inboxIE <- reactive({
  data <- q5IEdata()
  data
})


q3data <- pollSpreadsheet(URL_Q3, 
                          c("Timestamp","Group","Participated","Concreteness", "Milestone"),
                          c("Group", "Participated"))

work <- reactive({
  data <- q3data()
  data
})

q4data <- pollSpreadsheet(URL_Q4, 
                          c("Timestamp","Group","Context","Problem", "Pedagogical", "Technological", "Nature"),
                          c("Group", "Nature"))

nabc1 <- reactive({
  data <- q4data()
  data
})

q6data <- pollSpreadsheet(URL_Q6, 
                          c("Timestamp","Group","Benefit","Current", "Alternative", "Milestone", "Next"),
                          c("Group"))

nabc2 <- reactive({
  data <- q6data()
  data
})


      count_words <- function(s){
        #count <- as.numeric(stri_stats_latex(s)['Words'])
        count <- vapply(strsplit(s, "\\W+"), length, integer(1))
        count
      }



```


Overall goals
=====================================  
    
Column 1
-------------------------------------

### Mutual awareness of workgroups

```{r}
INITIALAWA <- 0.2
# logistic curve: 100*(1/(1+exp(-x+log((1-INITIAL)/INITIAL))))
renderGauge({
    hw <- homework()
    coef_hw <- 0
    
    if(nrow(hw)>0){
      totalhomework <- nrow(hw) #Total responses
      coef_hw <- ((nrow(hw[hw$Homework=='Yes, fully',])+(nrow(hw[hw$Homework=='I just skimmed quickly through them',])/2)))/(totalhomework)# Count % of people that read fully, +half % people that skimmed
    }
    
    gr <- groups()
    coef_wmn <- 0
    coef_und <- 0
    if(nrow(gr)>0){
      wmn <- gr[,c("Attention.LivingLabs","Attention.STEM","Attention.InformalWP","Attention.Inclusive")]
      meltwmn <- melt(wmn)
      coef_wmn = mean(meltwmn$value)/10
  
      und <- gr[,c("Understanding.LivingLabs","Understanding.STEM","Understanding.InformalWP","Understanding.Inclusive")]
      meltund <- melt(und)
      coef_und = mean(meltund$value)/10
    }
    

    x <- coef_hw + coef_wmn + coef_und
    print(x)
    point <- 100*(1/(1+exp(-x+log((1-INITIALAWA)/INITIALAWA))))
    gauge(round(point), min = 0, max = 100, symbol = '%', gaugeSectors(
      success = c(80, 100), warning = c(40, 79), danger = c(0, 39)
    ))
})

```    

### Homework
    
```{r}

renderPlot({
              data <- homework()
              ggplot(data, aes(x=Homework, fill=Homework))+geom_bar()+theme_bw()
                })

```

### Subjective with-me-ness

```{r}

renderPlot({
              data <- groups()
              data.wmn <- data[,c("Attention.LivingLabs","Attention.STEM","Attention.InformalWP","Attention.Inclusive")]
              melted <- melt(data.wmn)
              ggplot(melted, aes(x=value, fill=variable))+geom_density(alpha=0.2)+theme_bw()+xlim(1,10)
                })

```

### Subjective understanding

```{r}

renderPlot({
              data <- groups()
              data.wmn <- data[,c("Understanding.LivingLabs","Understanding.STEM","Understanding.InformalWP","Understanding.Inclusive")]
              melted <- melt(data.wmn)
              ggplot(melted, aes(x=value, fill=variable))+geom_density(alpha=0.2)+theme_bw()+xlim(1,10)
                })

```

   
Column 2
-------------------------------------
   
### Awareness of LA {data-height=250}

```{r}
INITIALLA <- 0.3
# logistic curve: 100*(1/(1+exp(-x+log((1-INITIAL)/INITIAL))))
renderGauge({
    fb <- feedback()
    coef_teach <- 0
    coef_res <- 0
    coef_def <- 0
    
    if(nrow(fb)>0){
      data <- fb[,c("Apply.Teaching","Apply.Research")]
      data$Apply.Teaching <- convertFactor(data$Apply.Teaching)
      data$Apply.Research <- convertFactor(data$Apply.Research)
      melted <- melt(data)
      print(melted)
      
      defs <- fb[,c("LA.Definition","Timestamp")]
      defs$nwords <- sapply(defs$LA.Definition,FUN = count_words)
      print(defs)
      
      coef_teach <- (mean(melted[melted$variable=="Apply.Teaching","value"], na.rm = T)-3)/2 # How much the intention of apply is over average
      coef_res <- (mean(melted[melted$variable=="Apply.Research","value"], na.rm = T)-3)/2 # How much the intention of apply is over average
      coef_def <- mean(defs$nwords)/15 # How much people put in the definitions (baseline: 15 words)
    }
    

    


    x <- coef_teach + coef_res + coef_def
    print(x)
    point <- 100*(1/(1+exp(-x+log((1-INITIALLA)/INITIALLA))))
    gauge(round(point), min = 0, max = 100, symbol = '%', gaugeSectors(
      success = c(80, 100), warning = c(40, 79), danger = c(0, 39)
    ))
})

```    


### Application in teaching & research  {data-height=250}

```{r}
renderPlot({
              data <- feedback()
              data2 <- data[,c("Apply.Teaching","Apply.Research")]
              data2$Apply.Teaching <- convertFactor(data2$Apply.Teaching)
              data2$Apply.Research <- convertFactor(data2$Apply.Research)
              print(data2)
              melted <- melt(data2)
              print(melted)
              ggplot(melted, aes(y=value, x=variable, fill=variable))+geom_boxplot(alpha=0.2)+theme_bw()+ylim(1,5)+coord_flip()
                })
```


### Definitions of LA (cloud) {data-height=250}

```{r}

# Alternative: word cloud
renderPlot({
data <- feedback()
print(data$LA.Definition)
corpus <- Corpus(VectorSource(data$LA.Definition))
corpus <- tm_map(corpus, removePunctuation)
corpus <- tm_map(corpus, tolower)
corpus <- tm_map(corpus, removeWords, stopwords("english"))
corpus <- tm_map(corpus, stemDocument)
corpus <- tm_map(corpus, PlainTextDocument)
wordcloud(corpus, max.words=100, random.order=F)
})
```


### Definitions of LA (raw) {data-height=250}

```{r}

# Raw definitions
 renderText({
               data <- feedback()
               defs <- data$LA.Definition
               defs <- defs[nchar(defs)>2]
               textdefs <- paste(defs, collapse = " || ")
               textdefs
 })

```
 


   
Column 3
-------------------------------------
   
### Participation

```{r}
INITIALPART <- 0.2
# logistic curve: 100*(1/(1+exp(-x+log((1-INITIAL)/INITIAL))))
renderGauge({
  
    coef_goals <- 0
    data <- homework()
    if(nrow(data)>0){
      goals <- paste(data$Personal.Goals, collapse = "\n")
      lines <- strsplit(goals, '\n', fixed=T)[[1]]
      nlines <- length(lines[nchar(lines)>2])
      coef_goals <- 0.5*(nlines/nrow(data)) # half a point per additional goal per person
      print(coef_goals)
    }
    
    data <- data.frame()
    dataA <- inboxLL()
    if(nrow(dataA)>0) dataA$Group <- "LivingLabs"
    if(nrow(dataA)>0 & nrow(data)==0) data <- dataA
    else if(nrow(dataA)>0 & nrow(data)>0) data <- rbind(data, dataA)
    dataB <- inboxSTEM()
    if(nrow(dataB)>0) dataB$Group <- "STEM"
    if(nrow(dataB)>0 & nrow(data)==0) data <- dataB
    else if(nrow(dataB)>0 & nrow(data)>0) data <- rbind(data, dataB)
    dataC <- inboxIWP()
    if(nrow(dataC)>0) dataC$Group <- "InformalWP"
    if(nrow(dataC)>0 & nrow(data)==0) data <- dataC
    else if(nrow(dataC)>0 & nrow(data)>0) data <- rbind(data, dataC)
    dataD <- inboxIE()
    if(nrow(dataD)>0) dataD$Group <- "Inclusive"
    if(nrow(dataD)>0 & nrow(data)==0) data <- dataD
    else if(nrow(dataD)>0 & nrow(data)>0) data <- rbind(data, dataD)

    coef_inbox <- 0
    if(nrow(data)>0){
      coef_inbox <- nrow(data)/16 # Baseline: 4 ideas per group
      print(coef_inbox)
    }
    
    data <- feedback()
    coef_comments <- 0
    
    if(nrow(data)>0){
      fb <- paste(data$Comments, collapse=" ")
      poa_word_v <- get_tokens(fb, pattern = "\\W")
      syuzhet_vector <- get_sentiment(poa_word_v, method="syuzhet")
      coef_comments <- mean(syuzhet_vector)
      print(coef_comments)
    }
    
    data <- work()
    coef_part <- 0
    if(nrow(data)>0){
      coef_part <- (nrow(data[data$Participated=='Yes',])-
                    nrow(data[data$Participated=='No',])+
                           nrow(data[data$Participated=='Only through the anonymous group inbox',])*0.5)/nrow(data)
      print(coef_part)
    }
    
    x <- coef_inbox + coef_goals + coef_comments + coef_part
    print(x)
    point <- 100*(1/(1+exp(-x+log((1-INITIALPART)/INITIALPART))))
    gauge(round(point), min = 0, max = 100, symbol = '%', gaugeSectors(
      success = c(80, 100), warning = c(40, 79), danger = c(0, 39)
    ))
})

```    
 

### Additional goals

```{r}

renderValueBox({
              data <- homework()
              goals <- paste(data$Personal.Goals, collapse = "\n")
              lines <- strsplit(goals, '\n', fixed=T)[[1]]
              lines <- lines[nchar(lines)>2]
              valueBox(
                value=length(lines),
                icon = "fa-bullseye",
                color="primary")
                })

```   

### Personal goals

```{r}

renderText({
              data <- homework()
              goals <- paste(data$Personal.Goals, collapse = "\n")
              lines <- strsplit(goals, '\n', fixed=T)[[1]]
              lines <- lines[nchar(lines)>2]
              paste(lines, collapse = " | ")
})
```

### Ideas in inboxes

```{r}
renderPlot({
  data <- data.frame()
  dataA <- inboxLL()
  if(nrow(dataA)>0) dataA$Group <- "LivingLabs"
  if(nrow(dataA)>0 & nrow(data)==0) data <- dataA
  else if(nrow(dataA)>0 & nrow(data)>0) data <- rbind(data, dataA)
  dataB <- inboxSTEM()
  if(nrow(dataB)>0) dataB$Group <- "STEM"
  if(nrow(dataB)>0 & nrow(data)==0) data <- dataB
  else if(nrow(dataB)>0 & nrow(data)>0) data <- rbind(data, dataB)
  dataC <- inboxIWP()
  if(nrow(dataC)>0) dataC$Group <- "InformalWP"
  if(nrow(dataC)>0 & nrow(data)==0) data <- dataC
  else if(nrow(dataC)>0 & nrow(data)>0) data <- rbind(data, dataC)
  dataD <- inboxIE()
  if(nrow(dataD)>0) dataD$Group <- "Inclusive"
  if(nrow(dataD)>0 & nrow(data)==0) data <- dataD
  else if(nrow(dataD)>0 & nrow(data)>0) data <- rbind(data, dataD)
  if(nrow(data)>0){
    t <- table(data$Group)
    t <- c(t, Total=nrow(data))
    df <- data.frame(num=t, var=factor(names(t)))
    ggplot(df, aes(x=var, y=num, fill=var))+geom_bar(stat='identity')+theme_bw() 
  }
})

```   


### Session feedback (polarity)

```{r}

renderValueBox({
              data <- feedback()
              fb <- paste(data$Comments, collapse=" ")
              poa_word_v <- get_tokens(fb, pattern = "\\W")
              print(paste("feedback:",poa_word_v))
              syuzhet_vector <- get_sentiment(poa_word_v, method="syuzhet")
              valueBox(
                value=round(mean(syuzhet_vector), digits=3),
                icon = "fa-smile-o",
                color="primary")
                })



```   

Living Labs
=====================================  
    
Column 1
-------------------------------------
    
### Group formation
    

```{r}
INITIALGRLL <- 0.5
# logistic curve: 100*(1/(1+exp(-x+log((1-INITIAL)/INITIAL))))
renderGauge({
  
      gr <- groups()

      coef_cores <- 0
      coef_periph <- 0
      if(nrow(gr)>0){
        members <- gr[,c("Implication.LivingLabs","Name","Email")]
        cores <- members[regexpr('core',members$Implication.LivingLabs)!=-1,]
        print(cores)
        periph <-  members[regexpr('loop',members$Implication.LivingLabs)!=-1,]
        print(periph)
        
        coef_cores <- as.numeric(nrow(cores)>1)
        coef_periph <- as.numeric(nrow(periph)>0)
      }
    

    x <- coef_cores + coef_periph
    print(x)
    point <- 100*(1/(1+exp(-x+log((1-INITIALGRLL)/INITIALGRLL))))
    gauge(round(point), min = 0, max = 100, symbol = '%', gaugeSectors(
      success = c(80, 100), warning = c(40, 79), danger = c(0, 39)
    ))
})

```    

### Core/Peripheric Members


```{r}

renderValueBox({
              gr <- groups()

              if(nrow(gr)>0){
                members <- gr[,c("Implication.LivingLabs","Name","Email")]
                cores <- members[regexpr('core',members$Implication.LivingLabs)!=-1,]
                print(cores)
                periph <-  members[regexpr('loop',members$Implication.LivingLabs)!=-1,]
                print(periph)
                
                message <- paste(nrow(cores)," core /",nrow(periph), "peripheral")
                valueBox(
                  value=message,
                  icon = "fa-balance-scale",
                  color="success")
                }
              })

```

### Core Members

```{r}

renderTable({
              gr <- groups()

              if(nrow(gr)>0){
                members <- gr[,c("Implication.LivingLabs","Name","Email")]
                cores <- members[regexpr('core',members$Implication.LivingLabs)!=-1,]
                print(cores)
                periph <-  members[regexpr('loop',members$Implication.LivingLabs)!=-1,]
                print(periph)
                cores[,c(2:3)]
              }
            })

```

### Peripheric Members

```{r}

renderTable({
              gr <- groups()

              if(nrow(gr)>0){
                members <- gr[,c("Implication.LivingLabs","Name","Email")]
                cores <- members[regexpr('core',members$Implication.LivingLabs)!=-1,]
                print(cores)
                periph <-  members[regexpr('loop',members$Implication.LivingLabs)!=-1,]
                print(periph)
                periph[,c(2:3)]
              }
            })

```

### Group's Email List
    
```{r}

renderText({
              gr <- groups()

              message <- ""
              if(nrow(gr)>0){
                members <- gr[,c("Implication.LivingLabs","Name","Email")]
                cores <- members[regexpr('core',members$Implication.LivingLabs)!=-1,]
                print(cores)
                periph <-  members[regexpr('loop',members$Implication.LivingLabs)!=-1,]
                print(periph)
                message <- paste(cores$Email, periph$Email, sep=", ", collapse = ", ")
              }
              message
            })

```


   
Column 2
-------------------------------------
   
### Concrete project

```{r}
INITIALPRJLL <- 0.3
# logistic curve: 100*(1/(1+exp(-x+log((1-INITIAL)/INITIAL))))
renderGauge({
  
      q4 <- nabc1()
      coef_nat <- 0
      if(nrow(q4)>0 & nrow(q4[regexpr('Living',q4$Group)!=-1,])>0){
        nature <- q4[regexpr('Living',q4$Group)!=-1,"Nature"]
        
        message <- as.character(nature)
        message <- paste(message, collapse = ", ")
        if(nchar(message)>0) coef_nat <- 1
      }

      data <- work()
      coef_peer <- 0
      if(nrow(data)>0 & nrow(data[regexpr('Living',data$Group)!=-1,])>0){
          data2 <- data[regexpr('Living',data$Group)!=-1,]
          coef_peer <- (mean(data2$Concreteness)-4)/3
      }

      data <- inboxLL()
      coef_sent <- 0
      if(nrow(data)>0){
        fb <- paste(data$Idea, collapse=" ")
        poa_word_v <- get_tokens(fb, pattern = "\\W")
        print(paste("ll inbox:",poa_word_v))
        syuzhet_vector <- get_sentiment(poa_word_v, method="syuzhet")
        coef_sent <- round(mean(syuzhet_vector), digits=3)
      }

      
      q4 <- nabc1()
      q6 <- nabc2()
      
      counts <- data.frame(Context=c(0),Problem=c(0),Pedagogical=c(0), Technological=c(0),
                           Benefit=c(0), Current=c(0), Alternative=c(0), Milestone=c(0))
      if(nrow(q4)>0 | nrow(q6)>0){
        if(nrow(q4)>0 & nrow(q4[regexpr('Living',q4$Group)!=-1,])>0){
          q4ll <- q4[regexpr('Living',q4$Group)!=-1,]
          context <- q4ll[,c("Context","Timestamp")]
          counts[1,'Context'] <- sum(sapply(context$Context,FUN = count_words))
          problem <- q4ll[,c("Problem","Timestamp")]
          counts[1,'Problem'] <- sum(sapply(problem$Problem,FUN = count_words))
          pedag <- q4ll[,c("Pedagogical","Timestamp")]
          counts[1,'Pedagogical'] <- sum(sapply(pedag$Pedagogical,FUN = count_words))
          tech <- q4ll[,c("Technological","Timestamp")]
          counts[1,'Technological'] <- sum(sapply(tech$Technological,FUN = count_words))
        }
        if(nrow(q6)>0 & nrow(q6[regexpr('Living',q6$Group)!=-1,])>0){
          q6ll <- q6[regexpr('Living',q6$Group)!=-1,]
          print(q6ll)
          ben <- q6ll[,c("Benefit","Timestamp")]
          counts[1,'Benefit'] <- sum(sapply(ben$Benefit,FUN = count_words))
          curr <- q6ll[,c("Current","Timestamp")]
          counts[1,'Current'] <- sum(sapply(curr$Current,FUN = count_words))
          alt <- q6ll[,c("Alternative","Timestamp")]
          counts[1,'Alternative'] <- sum(sapply(alt$Alternative,FUN = count_words))
          mil <- q6ll[,c("Milestone","Timestamp")]
          counts[1,'Milestone'] <- sum(sapply(mil$Milestone,FUN = count_words))
        }
      }
      
      melted <- melt(counts)
      coef_prop <- sum(melted$value>30)/8 # We count how many fields have more than 30 words
      print("coef_prop")
      print(coef_prop)

    x <- coef_nat + coef_peer + coef_sent + coef_prop
    print(x)
    point <- 100*(1/(1+exp(-x+log((1-INITIALPRJLL)/INITIALPRJLL))))
    gauge(round(point), min = 0, max = 100, symbol = '%', gaugeSectors(
      success = c(80, 100), warning = c(40, 79), danger = c(0, 39)
    ))
})

```    


### Nature of project {data-height=200}

```{r}

renderText({
              q4 <- nabc1()
              message <- ""
              if(nrow(q4)>0 & nrow(q4[regexpr('Living',q4$Group)!=-1,])>0){
                nature <- q4[regexpr('Living',q4$Group)!=-1,"Nature"]
                
                message <- as.character(nature)
                message <- paste(message, collapse = ", ")
              }
              message
            })

```

### Peer assessment concreteness

```{r}

renderPlot({
              data <- work()
              
              if(nrow(data)>0 & nrow(data[regexpr('Living',data$Group)!=-1,])>0){
                data2 <- data[regexpr('Living',data$Group)!=-1,]
                ggplot(data2, aes(x=Concreteness, fill="red"))+geom_density(alpha=0.2)+theme_bw()+xlim(1,7)+geom_vline(xintercept = mean(data2$Concreteness))
              }
              
                })
```

### Inbox's sentiment

```{r}

renderValueBox({
              data <- inboxLL()
              val <- 0
              if(nrow(data)>0){
                fb <- paste(data$Idea, collapse=" ")
                poa_word_v <- get_tokens(fb, pattern = "\\W")
                print(paste("ll inbox:",poa_word_v))
                syuzhet_vector <- get_sentiment(poa_word_v, method="syuzhet")
                val <- round(mean(syuzhet_vector), digits=3)
              }
              
              valueBox(
                value=val,
                icon = "fa-smile-o",
                color="primary")
            })



```   

### Word count in proposal {data-height=700}

```{r}

renderPlot({
              q4 <- nabc1()
              q6 <- nabc2()
              
              counts <- data.frame(Context=c(0),Problem=c(0),Pedagogical=c(0), Technological=c(0),
                                   Benefit=c(0), Current=c(0), Alternative=c(0), Milestone=c(0))

              if(nrow(q4)>0 | nrow(q6)>0){
                if(nrow(q4)>0 & nrow(q4[regexpr('Living',q4$Group)!=-1,])>0){
                  q4ll <- q4[regexpr('Living',q4$Group)!=-1,]
                  context <- q4ll[,c("Context","Timestamp")]
                  counts[1,'Context'] <- sum(sapply(context$Context,FUN = count_words))
                  problem <- q4ll[,c("Problem","Timestamp")]
                  counts[1,'Problem'] <- sum(sapply(problem$Problem,FUN = count_words))
                  pedag <- q4ll[,c("Pedagogical","Timestamp")]
                  counts[1,'Pedagogical'] <- sum(sapply(pedag$Pedagogical,FUN = count_words))
                  tech <- q4ll[,c("Technological","Timestamp")]
                  counts[1,'Technological'] <- sum(sapply(tech$Technological,FUN = count_words))
                }
                if(nrow(q6)>0 & nrow(q6[regexpr('Living',q6$Group)!=-1,])>0){
                  q6ll <- q6[regexpr('Living',q6$Group)!=-1,]
                  print(q6ll)
                  ben <- q6ll[,c("Benefit","Timestamp")]
                  counts[1,'Benefit'] <- sum(sapply(ben$Benefit,FUN = count_words))
                  curr <- q6ll[,c("Current","Timestamp")]
                  counts[1,'Current'] <- sum(sapply(curr$Current,FUN = count_words))
                  alt <- q6ll[,c("Alternative","Timestamp")]
                  counts[1,'Alternative'] <- sum(sapply(alt$Alternative,FUN = count_words))
                  mil <- q6ll[,c("Milestone","Timestamp")]
                  counts[1,'Milestone'] <- sum(sapply(mil$Milestone,FUN = count_words))
                }
              }
              
              melted <- melt(counts)
              
              ggplot(melted, aes(x=variable, y=value, fill=variable))+geom_bar(stat='identity', alpha=0.2)+theme_bw()+coord_flip()
              
              
                })
```

   
Column 3
-------------------------------------
   
### Next steps

```{r}
INITIALNXTLL <- 0.2
# logistic curve: 100*(1/(1+exp(-x+log((1-INITIAL)/INITIAL))))
renderGauge({

    q6 <- nabc2()
    coef_steps <- 0
    coef_ass <- 0
    coef_dat <- 0
    if(nrow(q6)>0 & nrow(q6[regexpr('Living',q6$Group)!=-1,])>0){
      data <- q6[regexpr('Living',q6$Group)!=-1,]
      nexts <- paste(data$Next, collapse = "\n")
      lines <- strsplit(nexts, '\n', fixed=T)[[1]]
      nlines <- length(lines[nchar(lines)>2])
      coef_steps <- nlines/3
      
      assigned <- length(lines[regexpr('\\]',lines)!=-1])
      dated <- length(lines[regexpr('\\)',lines)!=-1])
      coef_ass <- assigned/nlines
      coef_data <- dated/nlines
    }

    data <- work()
    coef_peer <- 0   
    if(nrow(data)>0 & nrow(data[regexpr('Living',data$Group)!=-1,])>0){
      data2 <- data[regexpr('Living',data$Group)!=-1,]
      coef_peer <- (mean(data2$Milestone)-4)/3
    }
  

    x <- coef_steps + coef_ass + coef_dat + coef_peer
    print(x)
    point <- 100*(1/(1+exp(-x+log((1-INITIALNXTLL)/INITIALNXTLL))))
    gauge(round(point), min = 0, max = 100, symbol = '%', gaugeSectors(
      success = c(80, 100), warning = c(40, 79), danger = c(0, 39)
    ))
})

```    

### Total next steps


```{r}
renderValueBox({
  q6 <- nabc2()
  nlines <- 0
  if(nrow(q6)>0 & nrow(q6[regexpr('Living',q6$Group)!=-1,])>0){
    data <- q6[regexpr('Living',q6$Group)!=-1,]
    nexts <- paste(data$Next, collapse = "\n")
    lines <- strsplit(nexts, '\n', fixed=T)[[1]]
    nlines <- length(lines[nchar(lines)>2])
    
  }
  valueBox(
    value=nlines,
    icon = "fa-balance-scale",
    color="success")

})
```

### Next steps with date / assignee

```{r}
renderValueBox({
  q6 <- nabc2()
  message <- 0
  if(nrow(q6)>0 & nrow(q6[regexpr('Living',q6$Group)!=-1,])>0){
    data <- q6[regexpr('Living',q6$Group)!=-1,]
    nexts <- paste(data$Next, collapse = "\n")
    lines <- strsplit(nexts, '\n', fixed=T)[[1]]
    lines <- lines[nchar(lines)>2]
    nlines <- length(lines)
    assigned <- length(lines[regexpr('\\]',lines)!=-1])
    dated <- length(lines[regexpr('\\)',lines)!=-1])
    message <- paste(assigned, "assigned /", dated, "dated")
  }
  valueBox(
    value=message,
    icon = "fa-balance-scale",
    color="success")

})
```

### Peer assessment milestone

```{r}

renderPlot({
              data <- work()
              
              if(nrow(data)>0 & nrow(data[regexpr('Living',data$Group)!=-1,])>0){
                data2 <- data[regexpr('Living',data$Group)!=-1,]
                ggplot(data2, aes(x=Milestone, fill="red"))+geom_density(alpha=0.2)+theme_bw()+xlim(1,7)+geom_vline(xintercept = mean(data2$Milestone))
              }
              
                })
```
